spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update